### ISSUE TITLE
NameError: name 'get_conversation_chain' is not defined

### ISSUE THREAD

**Issue by peter-dirickson** [aws-samples/aurora-postgresql-pgvector#62]
Using conda and after install all requirements, running `streamlit run rag_app.py --server.port 8080` I get this error:

```
Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/llm/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/Users/peter.dirickson/workspace/playground/aurora-postgresql-pgvector/02_RetrievalAugmentedGeneration/02_QuestionAnswering_Bedrock_LLMs/rag_app.py", line 165, in <module>
    main()
  File "/Users/peter.dirickson/workspace/playground/aurora-postgresql-pgvector/02_RetrievalAugmentedGeneration/02_QuestionAnswering_Bedrock_LLMs/rag_app.py", line 86, in main
    st.session_state.conversation = get_conversation_chain(get_vectorstore(None))
                                    ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_conversation_chain' is not defined
```

**Comment by shayons** [comment]
Fixed
